# Generated by Django 5.2 on 2025-06-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poster',
            options={'verbose_name': 'Мероприятиe', 'verbose_name_plural': 'Мероприятия'},
        ),
    ]
