# Generated by Django 5.2 on 2025-06-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_alter_poster_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='date_posted',
            field=models.DateField(),
        ),
    ]
