# Generated by Django 5.2 on 2025-06-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_drink_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='composition',
            field=models.TextField(default='Состав на подтверждении'),
            preserve_default=False,
        ),
    ]
